package arith;

public class CausedExceptionTest {
    public static void main(String[] args) {
        
    }
}
